import { Product, ProductCategory } from "@/features/products/types/product.types";

const products: Product[] = [
  // Snacks & Starters
  {
    id: "sn-1",
    slug: "mulakbajji-chutney",
    title: "Mulakbajji Chutney",
    description: "Crispy fried mulakbajji served with spicy chutney.",
    category: "snacks-starters",
    dietaryType: "veg",
    status: "coming_soon",
  },
  {
    id: "sn-2",
    slug: "banana-fritters-beef-fry",
    title: "Banana Fritters & Beef Fry",
    description: "Kerala's iconic combo: sweet pazhampori with spicy beef fry.",
    category: "snacks-starters",
    dietaryType: "non-veg",
    status: "coming_soon",
  },
  {
    id: "sn-3",
    slug: "sweet-coin-porotta",
    title: "Sweet Coin Porotta",
    category: "snacks-starters",
    dietaryType: "veg",
    status: "coming_soon",
  },
  {
    id: "sn-4",
    slug: "egg-puffs-egg-roll",
    title: "Egg Puffs & Egg Roll",
    category: "snacks-starters",
    dietaryType: "non-veg",
    status: "coming_soon",
  },
  {
    id: "sn-5",
    slug: "veg-puffs-veg-roll",
    title: "Veg Puffs & Veg Roll",
    category: "snacks-starters",
    dietaryType: "veg",
    status: "coming_soon",
  },
  {
    id: "sn-6",
    slug: "chicken-puffs",
    title: "Chicken Puffs",
    category: "snacks-starters",
    dietaryType: "non-veg",
    status: "coming_soon",
  },
  {
    id: "sn-7",
    slug: "veg-cocktail-samosa",
    title: "Veg Cocktail Samosa",
    category: "snacks-starters",
    dietaryType: "veg",
    status: "coming_soon",
  },
  {
    id: "sn-8",
    slug: "chicken-cocktail-samosa",
    title: "Chicken Cocktail Samosa",
    category: "snacks-starters",
    dietaryType: "non-veg",
    status: "coming_soon",
  },
  {
    id: "sn-9",
    slug: "unnakaya",
    title: "Unnakaya",
    category: "snacks-starters",
    dietaryType: "veg",
    status: "coming_soon",
  },
  {
    id: "sn-10",
    slug: "chicken-cutlet",
    title: "Chicken Cutlet",
    category: "snacks-starters",
    dietaryType: "non-veg",
    status: "coming_soon",
  },
  {
    id: "sn-11",
    slug: "paneer-tikka",
    title: "Paneer Tikka",
    category: "snacks-starters",
    dietaryType: "veg",
    status: "coming_soon",
  },
  {
    id: "sn-12",
    slug: "chicken-strips-coleslaw",
    title: "Chicken Strips & Coleslaw",
    category: "snacks-starters",
    dietaryType: "non-veg",
    status: "coming_soon",
  },
  {
    id: "sn-13",
    slug: "crispy-fried-vegetables",
    title: "Crispy Fried Vegetables",
    category: "snacks-starters",
    dietaryType: "veg",
    status: "coming_soon",
  },
  {
    id: "sn-14",
    slug: "chicken-roll-momos",
    title: "Chicken Roll & Momos",
    category: "snacks-starters",
    dietaryType: "non-veg",
    status: "coming_soon",
  },
  {
    id: "sn-15",
    slug: "garlic-bread",
    title: "Garlic Bread",
    category: "snacks-starters",
    dietaryType: "veg",
    status: "coming_soon",
  },
  {
    id: "sn-16",
    slug: "non-veg-basket",
    title: "Non Veg Basket",
    description: "Chicken, Beef, Pork",
    category: "snacks-starters",
    dietaryType: "non-veg",
    status: "coming_soon",
  },
  {
    id: "sn-17",
    slug: "cheese-rolls",
    title: "Cheese Rolls",
    category: "snacks-starters",
    dietaryType: "veg",
    status: "coming_soon",
  },
  {
    id: "sn-18",
    slug: "grilled-chicken-hummus",
    title: "Grilled Chicken & Hummus",
    category: "snacks-starters",
    dietaryType: "non-veg",
    status: "coming_soon",
  },
  {
    id: "sn-19",
    slug: "club-sandwich-veg",
    title: "Club Sandwich Veg",
    category: "snacks-starters",
    dietaryType: "veg",
    status: "coming_soon",
  },
  {
    id: "sn-20",
    slug: "club-sandwich-non-veg",
    title: "Club Sandwich Non Veg",
    category: "snacks-starters",
    dietaryType: "non-veg",
    status: "coming_soon",
  },
  {
    id: "sn-21",
    slug: "healthy-burrito-roll",
    title: "Healthy Burrito Roll",
    category: "snacks-starters",
    dietaryType: "mixed",
    status: "coming_soon",
  },

  // Vegetarian Meal Combos
  {
    id: "v-1",
    slug: "kerala-sadhya",
    title: "Kerala Sadhya",
    category: "vegetarian-meal-combos",
    dietaryType: "veg",
    status: "coming_soon",
    isFeatured: true,
  },
  {
    id: "v-2",
    slug: "ghee-idly-sambar-chutney",
    title: "Ghee Idly Sambar Chutney",
    category: "vegetarian-meal-combos",
    dietaryType: "veg",
    status: "coming_soon",
  },
  {
    id: "v-3",
    slug: "curd-rice",
    title: "Curd Rice",
    category: "vegetarian-meal-combos",
    dietaryType: "veg",
    status: "coming_soon",
  },
  {
    id: "v-4",
    slug: "puttu-kadala-salad",
    title: "Puttu Kadala Salad",
    category: "vegetarian-meal-combos",
    dietaryType: "veg",
    status: "coming_soon",
  },
  {
    id: "v-5",
    slug: "veg-biryani",
    title: "Veg Biryani",
    category: "vegetarian-meal-combos",
    dietaryType: "veg",
    status: "coming_soon",
  },

  // Non-Vegetarian Meal Combos
  {
    id: "nv-1",
    slug: "chicken-fry-rice-veggies",
    title: "Chicken Fry, Simple Chicken Curry, Rice & Veggies",
    category: "non-vegetarian-meal-combos",
    dietaryType: "non-veg",
    status: "coming_soon",
    isFeatured: true,
  },
  {
    id: "nv-2",
    slug: "chicken-biryani",
    title: "Chicken Biryani, Pickle, Salad",
    category: "non-vegetarian-meal-combos",
    dietaryType: "non-veg",
    status: "coming_soon",
  },
  {
    id: "nv-3",
    slug: "duck-curry-combo",
    title: "Duck Curry Combo",
    category: "non-vegetarian-meal-combos",
    dietaryType: "non-veg",
    status: "coming_soon",
  },
  {
    id: "nv-4",
    slug: "kallapam-fish-moile",
    title: "Kallapam & Fish Moile",
    category: "non-vegetarian-meal-combos",
    dietaryType: "non-veg",
    status: "coming_soon",
  },
  {
    id: "nv-5",
    slug: "ghee-rice-beef-roast-salad",
    title: "Ghee Rice Beef Roast Salad",
    category: "non-vegetarian-meal-combos",
    dietaryType: "non-veg",
    status: "coming_soon",
  },
];

export function getProducts(): Product[] {
  return products;
}

export function getProductsByCategory(category: ProductCategory | "all"): Product[] {
  if (category === "all") return products;
  return products.filter((p) => p.category === category);
}

export function getFeaturedProducts(): Product[] {
  return products.filter((p) => p.isFeatured);
}
